CREATE TABLE order_menu_items (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    order_id INT,
    menu_id INT,
    price FLOAT NOT NULL,
    quantity INT NOT NULL,
    discount FLOAT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (menu_id) REFERENCES menu(id) ON DELETE CASCADE
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;