CREATE TABLE menu (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    menu_name VARCHAR(100) NOT NULL,
    price FLOAT NOT NULL,
    description TEXT,
    image_url VARCHAR(255),
    category_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;